version: "3.8"

services:
  nginx:
    build: "./containers/nginx"
    ports:
      - "80:80"
      - "443:443"
    container_name: "nginx"
    volumes: 
      - ./certs:/etc/nginx/certs
    networks:
      - app
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
      - postgres

  node1:
    build: "./containers/node"
    ports:
      - "3000"
    networks:
      - app
      - db
      - amqp
    container_name: "node1"
    environment:
      - INSTANCE=node1
      - COUCHDB_USER=${COUCHDB_USR}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VOICE_RSS_KEY=${VOICE_RSS_KEY}
    depends_on:
      - rabbitmq
      - postgres
  
  node2:
    build: "./containers/node"
    container_name: "node2"
    ports:
      - "3000"
    networks:
      - app
      - db
      - amqp
    environment:
      - INSTANCE=node2
      - COUCHDB_USER=${COUCHDB_USR}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VOICE_RSS_KEY=${VOICE_RSS_KEY}
    depends_on:
      - rabbitmq
      - postgres

  node3:
    build: "./containers/node"
    ports:
      - "3000"
    container_name: "node3"
    networks:
      - app
      - db
      - amqp
    environment:
      - INSTANCE=node3
      - COUCHDB_USER=${COUCHDB_USR}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VOICE_RSS_KEY=${VOICE_RSS_KEY}
    depends_on:
      - rabbitmq
      - postgres

  postgres:
    build: "./containers/postgres"
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    networks:
      - db
    volumes: 
      - ./containers/postgres/data:/var/lib/postgresql/data
      - ./containers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  couchserver:
    build: "./containers/couchdb"
    restart: always
    container_name: "couch"
    ports:
      - "5984:5984"
    networks:
      - db
    environment:
      - COUCHDB_USER=${COUCHDB_USR}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
    volumes:
        - ./containers/couchdb/data:/opt/couchdb/data

  nodemailer:
    build: "./containers/nodemailer"
    container_name: "nodemailer"
    networks:
      - amqp
    depends_on:
      - rabbitmq
  
  rabbitmq:
    build: "./containers/rabbitmq"
    container_name: "rabbitmq"
    networks:
      - amqp

networks:
  app:
    driver: bridge
  db:
    driver: bridge
  amqp:
    driver: bridge