name: docker-compose-ci/cd
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  VOICE_RSS_KEY: ${{ secrets.VOICE_RSS_KEY }}
  SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: start docker
        run: docker-compose up -d
      - name: test connection
        run: curl http://localhost/